stages:
  - build
  - test
  - dockerize

variables:
  DOCKER_HOST: "tcp://localhost:2375"
  DOCKER_REGISTRY: "nexus.informatik.haw-hamburg.de"
  SERVICE_NAME: "icc-k8s-ldap"
cache:
  paths:
    - vendor

before_script:
  - git config --global http.sslVerify true
  - mkdir -p $GOPATH/src/gitlab.informatik.haw-hamburg.de/icc/kubernetes-ldap/
  - mv ./* $GOPATH/src/gitlab.informatik.haw-hamburg.de/icc/kubernetes-ldap/
  - cd $GOPATH/src/gitlab.informatik.haw-hamburg.de/icc/kubernetes-ldap/
  - go get -u github.com/golang/dep/cmd/dep

buildAndTest:
  stage: test
  image: nexus.informatik.haw-hamburg.de/golang:1.9
  variables:
    CGO_ENABLED: "0"
    GOOS: "linux"
  script:
    - dep ensure -v
    - go test gitlab.informatik.haw-hamburg.de/icc/kubernetes-ldap/
    - go build -a -installsuffix cgo gitlab.informatik.haw-hamburg.de/icc/kubernetes-ldap
    - mv ./kubernetes-ldap /$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/icc-k8s-ldap
  artifacts:
    paths:
    - ./icc-k8s-ldap


deploy:
  stage: dockerize
  image: nexus.informatik.haw-hamburg.de/docker:stable-dind
  services:
    - nexus.informatik.haw-hamburg.de/docker:stable-dind
  before_script:
    - echo "before_script overriden"
  dependencies:
    - buildAndTest
  script:
    - docker build -t $SERVICE_NAME:latest .
    - docker tag $SERVICE_NAME:latest $DOCKER_REGISTRY/$SERVICE_NAME:$CI_PIPELINE_ID
    - docker tag $SERVICE_NAME:latest $DOCKER_REGISTRY/$SERVICE_NAME:latest
    - docker tag $SERVICE_NAME:latest $DOCKER_REGISTRY/$SERVICE_NAME:$CI_COMMIT_SHA
    - docker login -u $NEXUS_USER -p $NEXUS_PW $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$SERVICE_NAME:$CI_PIPELINE_ID
    - docker push $DOCKER_REGISTRY/$SERVICE_NAME:latest
    - docker push $DOCKER_REGISTRY/$SERVICE_NAME:$CI_COMMIT_SHA